### ISSUE TITLE
Getting the Http Status

### ISSUE THREAD

**Issue by jhnferraris** [christophwitzko/go-curl#5]
Hello,

I've noticed that we can get the Http Response of the server via `resp.Header.Get("Server")`.
What are other constants that can be passed to this method? Is their a constant to get the status code?

Thanks!

**Comment by christophwitzko** [comment]
Hi @jhnferraris,

`resp` is a [HTTP response](https://golang.org/pkg/net/http/#Response) object. That means `resp.StatusCode` should just work.

Have a great day,
Christoph
